PHPAY-24-phpstan-9: feat: refactor arch phpay class

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -20,6 +20,21 @@ echo "🟢 Pint Ok!"
 echo "\n"
 
 echo "============================================="
+echo "Running PHPStan tests 🧪"
+echo "============================================="
+
+pint_output=$(./vendor/bin/phpstan analyse -l 9 src tests 2>&1)
+
+if [ $? -ne 0 ]; then
+    echo "Pint tests failed. Please fix the issues before pushing."
+    exit 1
+fi
+
+echo "🟢 PHPStan Ok!"
+
+echo "\n"
+
+echo "============================================="
 echo "Running pest tests 🧪"
 echo "============================================="
 
